#!/bin/bash
#
### BEGIN INIT INFO
# Provides: bm-agent-client
# Required-Start: $syslog $network
# Required-Stop: $syslog $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: BM agent client.
# Description: init system for BlueMind agent client.
### END INIT INFO

[ -f /lib/init/vars.sh ] && source /lib/init/vars.sh
if [ "$VERBOSE" == "yes" ]; then
	set -x
fi

BM_SERVICE="BlueMind agent client"

PATH=/sbin:/usr/sbin:/bin:/usr/bin
if [ -e /usr/bin/bm_java_home ]; then
    export JAVA_HOME=`/usr/bin/bm_java_home`
else
    export JAVA_HOME=`/usr/share/bm-agent-client/bm_java_home`
fi
PATH=$JAVA_HOME/bin:$PATH

test -f $JAVA_HOME/bin/java || {
    echo "JDK not found in JAVA_HOME: $JAVA_HOME"
    exit 1
}


bmagentclient_pid=/var/run/bm-agent-client.pid
bmagentclient_home=/usr/share/bm-agent-client
bmagentclient_logs=/var/log/bm-agent-client/bm-agent-client.log
jps=$JAVA_HOME/bin/jps

bmagentclient_running() {
    test -f ${bmagentclient_pid} || return 1
    supposed_pid=`cat ${bmagentclient_pid}`

    kill -0 ${supposed_pid} >/dev/null 2>&1
    ret=$?

    if [ ${ret} -ne 0 ]; then
        rm -f ${bmagentclient_pid} > /dev/null 2>&1 || true
    fi

    return ${ret}
}

start_bmagentclient() {
    bmagentclient_running && {
	echo "${BM_SERVICE} client already running."
        return 0
    }

    ${bmagentclient_home}/bm-agent-client 0>/dev/null 1>/dev/null 2>/dev/null 3>/dev/null &
    new_pid=$!
    echo $new_pid > $bmagentclient_pid 
    echo -n "Starting client ${BM_SERVICE} (PID: `cat ${bmagentclient_pid}`)"
    bmagentclient_running
    running=$?

    if [ ${running} -eq 0 ]; then
        echo ": done"
    else
        echo ": fail"
    fi

    return ${running}
}

stop_bmagentclient() {
    bmagentclient_running || {
	echo "${BM_SERVICE} client not running."
	return 0
    }

    if [ -f /sbin/start-stop-daemon ]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile ${bmagentclient_pid}
    else
        kill -TERM `cat ${bmagentclient_pid}`
    fi

    echo -n "Waiting for ${BM_SERVICE} client shutdown."
    count=0
    while bmagentclient_running; do
	echo -n "."
	sleep 0.5
	count=$((${count}+1))
        if [ ${count} -gt 10 ]; then
          kill -9 `cat ${bmagentclient_pid}` || true
	  break
        fi
    done
    rm -f ${bmagentclient_pid}
    echo ""
}

status_bmagentclient() {
    bmagentclient_running || {
        echo "${BM_SERVICE} client not running."
        return 3
    }

   return 0
}

case "$1" in
    start)
        start_bmagentclient
        ret=$?
        ;;
    
    stop)
        stop_bmagentclient
        ret=$?
        ;;
    status)
	    status_bmagentclient
        ret=$?
	;;
    restart)
        stop_bmagentclient
        start_bmagentclient
        ret=$?
        ;;
esac

exit $ret
